strategy:
  bintest:
    module: bintest
    class: BintestStrategy
    config: BintestConfig
    params:
      instrument_client: binance_futures

node:
  logging:
    strategy_log_level: INFO

  data:
    clients:
      binance_futures:
        enabled: true
        markets:
          - symbol: BTC/USDT
            timeframe: 1s

  exec:
    engine:
      reconciliation: false
      reconciliation_scope: null

    clients:
      binance_futures:
        enabled: false
        markets: []
