strategy:
  name: xgbfunding
  modes: [testnet, live]
  params:
    trade_notional: "8"
    min_rate_bps: "30"
    trade_symbols: all
    exclude_symbols: [LYN, BEAT, PIPPIN, RAVE, SOON, SENT, ORCA]
    pre_sec: 2.5
    entry_sec: 1.5
    pre_deadline: 1
    entry_before: 0.5
    exit_sec: 0.1
    post_sec: 10
    api_url: https://fapi.binance.com
    api_timeout: 0.8
    proxy_url: http://127.0.0.1:7890
    stop_close: true
    model_horizon_ms: 500
    model_path: models/node_select_outputs/node_select_500ms.joblib
    feature_path: models/funding_return_outputs/event_features.parquet

exchange:
  venue: BINANCE

live:
  markets: all
  strategy_log_level: INFO

backtest:
  markets: [1000000BOB/USDT, AXS/USDT, BARD/USDT, CFG/USDT, COS/USDT,
            DRIFT/USDT, ENJ/USDT, ENSO/USDT, GTC/USDT, GUA/USDT,
            KITE/USDT, LYN/USDT, NOM/USDT, ORCA/USDT, POWER/USDT,
            RAVE/USDT, RIVER/USDT, SAHARA/USDT, SIREN/USDT, SOON/USDT,
            STEEM/USDT, SIGN/USDT, CHIP/USDT, MBOX/USDT, VIC/USDT,
            BB/USDT, SOLV/USDT, MEGA/USDT, INJ/USDT, DOGS/USDT,
            SAPIEN/USDT, KERNEL/USDT, COMP/USDT, SAGA/USDT, MOVE/USDT]
  starting_balance: "100000 USDT"
  account_type: MARGIN
  oms_type: NETTING
  log_level: INFO
  log_bypass: true
  data:
    limit: 1000
    batches: 1
  instrument:
    settlement_currency: USDT
    is_inverse: false
    price_precision: 5
    size_precision: 1
    price_increment: "0.00010"
    size_increment: "0.1"
    multiplier: "1"
    min_quantity: "0.1"
    max_quantity: "1000000"
    min_notional: "5"
    max_price: "1000000"
    margin_init: "1"
    margin_maint: "1"
    maker_fee: "0.0002"
    taker_fee: "0.0005"
