strategy:
  module: quote_delay_test
  class: QuoteDelayStrategy
  config: QuoteDelayConfig
  params:
    instruments: enabled
    run_seconds: 60
    summary_interval_sec: 5

logging:
  strategy_log_level: INFO

data:
  clients:
    binance_futures:
      enabled: true
      markets:
        - KORU

    okx_swap:
      enabled: false
      markets: []

exec:
  engine:
    reconciliation: false
    reconciliation_scope: null

  clients:
    binance_futures:
      enabled: false
      markets: []

    okx_swap:
      enabled: false
      markets: []
