from __future__ import annotations

import pandas as pd


COLUMN_LABELS = {
    "ts_event": "事件时间",
    "instrument_id": "标的",
    "order_side": "订单方向",
    "last_qty": "成交数量",
    "last_px": "成交价格",
    "commission": "手续费",
    "client_order_id": "客户端订单ID",
    "position_id": "仓位ID",
    "account_id": "账户ID",
    "account_type": "账户类型",
    "base_currency": "基础币种",
    "currency": "币种",
    "total": "总余额",
    "locked": "冻结余额",
    "free": "可用余额",
    "is_reported": "交易所上报",
    "reported": "交易所上报",
    "event_type": "事件类型",
    "info_type": "附加类型",
    "info_reason": "附加原因",
    "info": "附加信息",
    "side": "方向",
    "quantity": "数量",
    "event_side": "事件方向",
    "fill_quantity": "本次成交数量",
    "fill_price": "本次成交价格",
    "realized_pnl": "已实现盈亏",
    "adjustment_type": "调整类型",
    "quantity_change": "数量调整",
    "pnl_change": "盈亏调整",
    "reason": "原因",
    "strategy_id": "策略ID",
    "filled_qty": "已成交数量",
    "avg_px": "平均成交价",
    "commissions": "手续费合计",
    "status": "订单状态",
    "ts_init": "初始化时间",
    "ts_last": "最后更新时间",
    "entry": "开仓方向",
    "peak_qty": "最大持仓数量",
    "avg_px_open": "开仓均价",
    "avg_px_close": "平仓均价",
    "realized_return": "已实现收益率",
    "ts_opened": "开仓时间",
    "ts_closed": "平仓时间",
    "duration_ns": "持仓纳秒",
    "opening_order_id": "开仓订单ID",
    "closing_order_id": "平仓订单ID",
    "qty": "数量",
    "open_time": "开仓时间",
    "close_time": "平仓时间",
    "avg_open": "开仓均价",
    "avg_close": "平仓均价",
    "duration_min": "持仓分钟",
    "estimated_funding_income": "预估资金费收入",
    "actual_funding_income": "实际资金费收入",
    "funding_income": "资金费收入",
    "net_with_funding": "含资金费净收益",
    "funding_time": "资金费时间",
    "funding_rate": "资金费率",
    "local_time": "本地时间",
    "delta_to_funding_ms": "距资金费毫秒",
    "adverse_entry_move": "入场不利波动",
    "funding_income_time": "资金费到账时间",
    "funding_income_delta_ms": "资金费到账延迟毫秒",
    "funding_tran_id": "资金费流水ID",
    "bar_time": "行情时间",
    "interval_hours": "资金费间隔小时",
    "action": "动作",
    "bar_open": "行情开盘价",
    "bar_close": "行情收盘价",
    "notional": "名义价值",
    "income_time": "到账时间",
    "delta_ms": "延迟毫秒",
    "symbol": "交易对",
    "income": "收入",
    "asset": "资产",
    "income_type": "收入类型",
    "tran_id": "流水ID",
    "trade_id": "交易ID",
}


# 输出 CSV 前把内部英文列名改成中文。
def to_chinese_columns(df: pd.DataFrame) -> pd.DataFrame:
    return df.rename(columns=COLUMN_LABELS)
